name: flutter_sudoku
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  iconsax: ^0.0.8

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_spinkit: ^5.1.0
  sudoku_solver_generator: ^2.0.0
  wakelock_plus: ^1.0.0
  win32: ^5.8.0 # Mettez à jour à la dernière version
  google_mobile_ads: ^3.0.0
  fluttertoast: ^8.2.1


dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  confetti: ^0.7.0


  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFFFFF"  #
  adaptive_icon_foreground: "assets/app_icon.png"  #
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/language_EN.png
    - assets/language_TR.png
    - assets/app_icon.png
    - assets/

